FROM node:22-bookworm-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 make g++ git ffmpeg \
 && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm ci

# Run the bot
# CMD ["node", "src/index.js"]
COPY package*.json ./